// Mapa de corrección de nombres de anunciantes que llegan pegados desde BigQuery
// Clave: nombre exacto en BQ (mayúsculas, sin espacios)
// Valor: nombre legible para mostrar en la plataforma
module.exports = {
  ADILISPARAGUAY:              'Adilis Paraguay',
  AMANECERSA:                  'Amanecer S.A.',
  AMERICAMOVIL:                'América Móvil',
  ANDROMACO:                   'Andrómaco',
  ARCOIRISSA:                  'Arco Iris S.A.',
  ASEGURADORADELESTE:          'Aseguradora del Este',
  BANCOBASA:                   'Banco Basa',
  BANCOFAMILIAR:               'Banco Familiar',
  BARCOSYRODADOS:              'Barcos y Rodados',
  BCOCONTINENTAL:              'Banco Continental',
  BCOREGIONAL:                 'Banco Regional',
  BURGERKING:                  'Burger King',
  CAMARAPARAGUAYADELCLORO:     'Cámara Paraguaya del Cloro',
  CAMARAPYAPROCESADORES:       'Cámara PY de Procesadores',
  CASAESCAURIZA:               'Casa Escauriza',
  CASAGRUTER:                  'Casa Gruter',
  CASAPARANA:                  'Casa Paraná',
  CERVEZADIOSA:                'Cerveza Diosa',
  COLCHONESSUPERSPUMA:         'Colchones Superspuma',
  COLGATEPALMOLIVEPY:          'Colgate Palmolive PY',
  CONFEDSUDAMERICANADEFUTBOL:  'Conf. Sudamericana de Fútbol',
  COOP8DEMARZO:                'Coop. 8 de Marzo',
  COOPBINACIONALCABALLTDA:     'Coop. Binacional Caball Ltda.',
  COOPCOLONIASUNIDAS:          'Coop. Colonias Unidas',
  COOPERATIVACHORTITZER:       'Cooperativa Chortitzer',
  COOPERATIVALAHOLANDA:        'Cooperativa La Holanda',
  COOPJUDICIALLTDA:            'Coop. Judicial Ltda.',
  COOPMEDALLAMILAGROSA:        'Coop. Medalla Milagrosa',
  COOPMULTIACTIVAFERHEIM:      'Coop. Multiactiva Ferheim',
  COOPNEULAND:                 'Coop. Neuland',
  COOPUNIVERSITARIA:           'Coop. Universitaria',
  DELASOBERA:                  'De La Sobera',
  DINOHAUTECOIFFURE:           'Dino Haute Coiffure',
  DISTRIBUIDORADELPARAGUAY:    'Distribuidora del Paraguay',
  DISTRIBUIDORAGLORIA:         'Distribuidora Gloria',
  EMBOTELLADORACENTRAL:        'Embotelladora Central',
  EMBUTIDOSFRANZ:              'Embutidos Franz',
  ESTABLECIMIENTOLASCOLONIAS:  'Establecimiento Las Colonias',
  FABRICAPARAGUAYADESIERRAS:   'Fábrica Paraguaya de Sierras',
  FARMACEUTICAPY:              'Farmacéutica PY',
  FUNDPARAGUAYA:               'Fund. Paraguaya',
  GALERIAGUARANI:              'Galería Guaraní',
  GARDENGRUPO:                 'Garden Grupo',
  GARDENHOUSE:                 'Garden House',
  GENERALMOTORS:               'General Motors',
  GENOMMALAB:                  'Genomma Lab',
  GONZALEZGIMENEZ:             'González Giménez',
  GRANJAAVICOLALABLANCA:       'Granja Avícola La Blanca',
  GRUPOCAVALLARO:              'Grupo Cavallaro',
  HOLDINGGRUPOCARTES:          'Holding Grupo Cartes',
  HONORDEVICE:                 'Honor Device',
  INDUSTRIASYALIMENTOSVIERCI:  'Industrias y Alimentos Vierci',
  INESFLYBODY:                 'Inés Flybody',
  INTERFISABANCO:              'Interfisa Banco',
  ISISPHARMA:                  'Isis Pharma',
  JOSERUOTIYCIA:               'José Ruoti y Cía.',
  KIMBERLYCLARK:               'Kimberly Clark',
  LABGALENO:                   'Lab. Galeno',
  LABORATORIOBAGO:             'Laboratorio Bagó',
  LABORATORIOSALMOS:           'Laboratorios Almos',
  LABORATORIOSCATEDRAL:        'Laboratorios Catedral',
  LABORATORIOSIDUS:            'Laboratorios Idus',
  LABORATORIOSROEMMERSSACI:    'Laboratorios Roemmers S.A.C.I.',
  LACONSOLIDADA:               'La Consolidada',
  LALOTEADORA:                 'La Loteadora',
  LAMISIONERA:                 'La Misionera',
  LAQUIMICAFARMACEUTICA:       'La Química Farmacéutica',
  LASCALABORATORIOS:           'Lasca Laboratorios',
  LASERIMPORT:                 'Laser Import',
  MARISCALLOPEZSHOPPING:       'Mariscal López Shopping',
  MARTINMASI:                  'Martín Masi',
  MOLINOELPAIS:                'Molino El País',
  MONACOCOMERCIAL:             'Mónaco Comercial',
  MVCOMERCIAL:                 'MV Comercial',
  NICOLASGONZALEZODDONE:       'Nicolás González Oddone',
  PARAGUAYREFRESCOS:           'Paraguay Refrescos',
  PARAGUAYTRADING:             'Paraguay Trading',
  PASEOLAGALERIA:              'Paseo La Galería',
  PASTASDELESTE:               'Pastas del Este',
  PERFECTAAUTOMOTORES:         'Perfecta Automotores',
  PUMAENERGY:                  'Puma Energy',
  PUNTOFARMA:                  'Punto Farma',
  RAICESINMOBILIARIA:          'Raíces Inmobiliaria',
  SAMBARIESA:                  'Sambarie S.A.',
  SAMSUNGPARAGUAY:             'Samsung Paraguay',
  SANATORIOMIGONE:             'Sanatorio Migone',
  SANCAYETANOCOMERCIAL:        'San Cayetano Comercial',
  SANOFIAVENTISNPARAGUAY:      'Sanofi Aventis Paraguay',
  SANTACLARA:                  'Santa Clara',
  SANTAMARGARITA:              'Santa Margarita',
  SCAVONEHNOS:                 'Scavone Hnos.',
  SCJOHNSON:                   'SC Johnson',
  SERVICIOSDIGITALES:          'Servicios Digitales',
  SERVRAPIDOSDELPY:            'Serv. Rápidos del PY',
  SHOPPINGCHINA:               'Shopping China',
  SOLUCIONESLOGISTICAS:        'Soluciones Logísticas',
  SOUTHFOOD:                   'South Food',
  SUDAMERISBANK:               'Sudameris Bank',
  SUENIOLAR:                   'Sueñiolar',
  SUNSETCUBIERTAS:             'Sunset Cubiertas',
  TABACALERADELESTE:           'Tabacalera del Este',
  TINTORERIAIMPECABLE:         'Tintorería Impecable',
  UNIVAMERICANA:               'Univ. Americana',
  UNIVAUTONOMADELSUR:          'Univ. Autónoma del Sur',
  UNIVPOLITECNICAARTISTICAPY:  'Univ. Politécnica Artística PY',
  VIRGENDELROSARIO:            'Virgen del Rosario',
  VISIONBANCO:                 'Visión Banco',
  YERBAPAJARITO:               'Yerba Pajarito',
};
