// Mapas de corrección de valores que llegan pegados o en mayúsculas desde BigQuery

const anunciantes = {
  ADILISPARAGUAY:              'Adilis Paraguay',
  AMANECERSA:                  'Amanecer S.A.',
  AMERICAMOVIL:                'América Móvil',
  ANDROMACO:                   'Andrómaco',
  ARCOIRISSA:                  'Arco Iris S.A.',
  ASEGURADORADELESTE:          'Aseguradora del Este',
  BANCOBASA:                   'Banco Basa',
  BANCOFAMILIAR:               'Banco Familiar',
  BARCOSYRODADOS:              'Barcos y Rodados',
  BCOCONTINENTAL:              'Banco Continental',
  BCOREGIONAL:                 'Banco Regional',
  BURGERKING:                  'Burger King',
  CAMARAPARAGUAYADELCLORO:     'Cámara Paraguaya del Cloro',
  CAMARAPYAPROCESADORES:       'Cámara PY de Procesadores',
  CASAESCAURIZA:               'Casa Escauriza',
  CASAGRUTER:                  'Casa Gruter',
  CASAPARANA:                  'Casa Paraná',
  CERVEZADIOSA:                'Cerveza Diosa',
  COLCHONESSUPERSPUMA:         'Colchones Superspuma',
  COLGATEPALMOLIVEPY:          'Colgate Palmolive PY',
  CONFEDSUDAMERICANADEFUTBOL:  'Conf. Sudamericana de Fútbol',
  COOP8DEMARZO:                'Coop. 8 de Marzo',
  COOPBINACIONALCABALLTDA:     'Coop. Binacional Caball Ltda.',
  COOPCOLONIASUNIDAS:          'Coop. Colonias Unidas',
  COOPERATIVACHORTITZER:       'Cooperativa Chortitzer',
  COOPERATIVALAHOLANDA:        'Cooperativa La Holanda',
  COOPJUDICIALLTDA:            'Coop. Judicial Ltda.',
  COOPMEDALLAMILAGROSA:        'Coop. Medalla Milagrosa',
  COOPMULTIACTIVAFERHEIM:      'Coop. Multiactiva Ferheim',
  COOPNEULAND:                 'Coop. Neuland',
  COOPUNIVERSITARIA:           'Coop. Universitaria',
  DELASOBERA:                  'De La Sobera',
  DINOHAUTECOIFFURE:           'Dino Haute Coiffure',
  DISTRIBUIDORADELPARAGUAY:    'Distribuidora del Paraguay',
  DISTRIBUIDORAGLORIA:         'Distribuidora Gloria',
  EMBOTELLADORACENTRAL:        'Embotelladora Central',
  EMBUTIDOSFRANZ:              'Embutidos Franz',
  ESTABLECIMIENTOLASCOLONIAS:  'Establecimiento Las Colonias',
  FABRICAPARAGUAYADESIERRAS:   'Fábrica Paraguaya de Sierras',
  FARMACEUTICAPY:              'Farmacéutica PY',
  FUNDPARAGUAYA:               'Fund. Paraguaya',
  GALERIAGUARANI:              'Galería Guaraní',
  GARDENGRUPO:                 'Garden Grupo',
  GARDENHOUSE:                 'Garden House',
  GENERALMOTORS:               'General Motors',
  GENOMMALAB:                  'Genomma Lab',
  GONZALEZGIMENEZ:             'González Giménez',
  GRANJAAVICOLALABLANCA:       'Granja Avícola La Blanca',
  GRUPOCAVALLARO:              'Grupo Cavallaro',
  HOLDINGGRUPOCARTES:          'Holding Grupo Cartes',
  HONORDEVICE:                 'Honor Device',
  INDUSTRIASYALIMENTOSVIERCI:  'Industrias y Alimentos Vierci',
  INESFLYBODY:                 'Inés Flybody',
  INTERFISABANCO:              'Interfisa Banco',
  ISISPHARMA:                  'Isis Pharma',
  JOSERUOTIYCIA:               'José Ruoti y Cía.',
  KIMBERLYCLARK:               'Kimberly Clark',
  LABGALENO:                   'Lab. Galeno',
  LABORATORIOBAGO:             'Laboratorio Bagó',
  LABORATORIOSALMOS:           'Laboratorios Almos',
  LABORATORIOSCATEDRAL:        'Laboratorios Catedral',
  LABORATORIOSIDUS:            'Laboratorios Idus',
  LABORATORIOSROEMMERSSACI:    'Laboratorios Roemmers S.A.C.I.',
  LACONSOLIDADA:               'La Consolidada',
  LALOTEADORA:                 'La Loteadora',
  LAMISIONERA:                 'La Misionera',
  LAQUIMICAFARMACEUTICA:       'La Química Farmacéutica',
  LASCALABORATORIOS:           'Lasca Laboratorios',
  LASERIMPORT:                 'Laser Import',
  MARISCALLOPEZSHOPPING:       'Mariscal López Shopping',
  MARTINMASI:                  'Martín Masi',
  MOLINOELPAIS:                'Molino El País',
  MONACOCOMERCIAL:             'Mónaco Comercial',
  MVCOMERCIAL:                 'MV Comercial',
  NICOLASGONZALEZODDONE:       'Nicolás González Oddone',
  PARAGUAYREFRESCOS:           'Paraguay Refrescos',
  PARAGUAYTRADING:             'Paraguay Trading',
  PASEOLAGALERIA:              'Paseo La Galería',
  PASTASDELESTE:               'Pastas del Este',
  PERFECTAAUTOMOTORES:         'Perfecta Automotores',
  PUMAENERGY:                  'Puma Energy',
  PUNTOFARMA:                  'Punto Farma',
  RAICESINMOBILIARIA:          'Raíces Inmobiliaria',
  SAMBARIESA:                  'Sambarie S.A.',
  SAMSUNGPARAGUAY:             'Samsung Paraguay',
  SANATORIOMIGONE:             'Sanatorio Migone',
  SANCAYETANOCOMERCIAL:        'San Cayetano Comercial',
  SANOFIAVENTISNPARAGUAY:      'Sanofi Aventis Paraguay',
  SANTACLARA:                  'Santa Clara',
  SANTAMARGARITA:              'Santa Margarita',
  SCAVONEHNOS:                 'Scavone Hnos.',
  SCJOHNSON:                   'SC Johnson',
  SERVICIOSDIGITALES:          'Servicios Digitales',
  SERVRAPIDOSDELPY:            'Serv. Rápidos del PY',
  SHOPPINGCHINA:               'Shopping China',
  SOLUCIONESLOGISTICAS:        'Soluciones Logísticas',
  SOUTHFOOD:                   'South Food',
  SUDAMERISBANK:               'Sudameris Bank',
  SUENIOLAR:                   'Sueñiolar',
  SUNSETCUBIERTAS:             'Sunset Cubiertas',
  TABACALERADELESTE:           'Tabacalera del Este',
  TINTORERIAIMPECABLE:         'Tintorería Impecable',
  UNIVAMERICANA:               'Univ. Americana',
  UNIVAUTONOMADELSUR:          'Univ. Autónoma del Sur',
  UNIVPOLITECNICAARTISTICAPY:  'Univ. Politécnica Artística PY',
  VIRGENDELROSARIO:            'Virgen del Rosario',
  VISIONBANCO:                 'Visión Banco',
  YERBAPAJARITO:               'Yerba Pajarito',
};

const rubros = {
  agroindustriagranosyexportacion:       'Agroindustria · Granos y Exportación',
  agroindustrialacteos:                  'Agroindustria · Lácteos',
  agroindustriaporcina:                  'Agroindustria · Porcina',
  alimentacionaceites:                   'Alimentación · Aceites',
  alimentacionalimentosprocesados:       'Alimentación · Alimentos Procesados',
  alimentacionavicola:                   'Alimentación · Avícola',
  alimentacionbebidas:                   'Alimentación · Bebidas',
  alimentacionbebidasalcoholicas:        'Alimentación · Bebidas Alcohólicas',
  alimentacionbebidasnaturales:          'Alimentación · Bebidas Naturales',
  alimentacionbebidasnoalcoholicas:      'Alimentación · Bebidas No Alcohólicas',
  alimentacioncarnes:                    'Alimentación · Carnes',
  alimentacionconsumomasivo:             'Alimentación · Consumo Masivo',
  alimentaciondistribucion:              'Alimentación · Distribución',
  alimentacionembutidos:                 'Alimentación · Embutidos',
  alimentaciongolosinas:                 'Alimentación · Golosinas',
  alimentacionharinasyderivados:         'Alimentación · Harinas y Derivados',
  alimentacioninfusiones:                'Alimentación · Infusiones',
  alimentacionlacteos:                   'Alimentación · Lácteos',
  alimentacionmascotas:                  'Alimentación · Mascotas',
  alimentacionpanificados:               'Alimentación · Panificados',
  alimentacionpastas:                    'Alimentación · Pastas',
  alimentacionproductosnaturales:        'Alimentación · Productos Naturales',
  alimentacionrestaurantes:              'Alimentación · Restaurantes',
  alimentacionsnacks:                    'Alimentación · Snacks',
  alimentaciontabaco:                    'Alimentación · Tabaco',
  alimentacionyerbamateybebidas:         'Alimentación · Yerba Mate y Bebidas',
  apuestasjuegosdeazar:                  'Apuestas y Juegos de Azar',
  automotriz:                            'Automotriz',
  automotrizaccesoriosycubiertas:        'Automotriz · Accesorios y Cubiertas',
  automotrizconcesionaria:               'Automotriz · Concesionaria',
  automotrizfabricante:                  'Automotriz · Fabricante',
  automotrizmaquinarias:                 'Automotriz · Maquinarias',
  automotrizneumaticos:                  'Automotriz · Neumáticos',
  automotrizvehiculos:                   'Automotriz · Vehículos',
  bancamediosdepago:                     'Banca · Medios de Pago',
  bancaserviciosfinancieros:             'Banca y Servicios Financieros',
  bellezapeluqueriadelujo:               'Belleza · Peluquería de Lujo',
  bienesraicesdesarrolloinmobiliario:    'Bienes Raíces · Desarrollo Inmobiliario',
  climatizacionaireacondicionado:        'Climatización · Aire Acondicionado',
  comerciominorista:                     'Comercio Minorista',
  consumomasivohigiene:                  'Consumo Masivo · Higiene',
  consumomasivohigienebucal:             'Consumo Masivo · Higiene Bucal',
  consumomasivohigieneyalimentos:        'Consumo Masivo · Higiene y Alimentos',
  consumomasivolimpieza:                 'Consumo Masivo · Limpieza',
  cooperativafinanciera:                 'Cooperativa Financiera',
  cosmeticacuidadopersonal:              'Cosmética · Cuidado Personal',
  cosmeticanaturalysaludable:            'Cosmética · Natural y Saludable',
  cosmeticaproductosnaturales:           'Cosmética · Productos Naturales',
  cosmeticarepelentecorporal:            'Cosmética · Repelente Corporal',
  deportesorganizacioncontinental:       'Deportes · Organización Continental',
  distribucionconsumomasivo:             'Distribución Consumo Masivo',
  distribuidoradepeliculas:              'Distribuidora de Películas',
  educacionuniversidadprivada:           'Educación · Universidad Privada',
  energiacombustibles:                   'Energía y Combustibles',
  energiahidroelectrica:                 'Energía · Hidroeléctrica',
  finanzascooperativa:                   'Finanzas · Cooperativa',
  higieneylimpiezadomestica:             'Higiene y Limpieza Doméstica',
  higieneypapeltissue:                   'Higiene · Papel Tissue',
  holdingmultirubro:                     'Holding Multirubro',
  importacionydistribucionmultirubro:    'Importación y Distribución Multirubro',
  industriaherramientas:                 'Industria · Herramientas',
  industriaquimica:                      'Industria Química',
  inmobiliariabienesraices:              'Inmobiliaria · Bienes Raíces',
  inmobiliarialoteamientos:              'Inmobiliaria · Loteamientos',
  inmobiliariaurbanizaciones:            'Inmobiliaria · Urbanizaciones',
  juridicoservicioslegales:              'Jurídico · Servicios Legales',
  logisticatransporteydistribucion:      'Logística · Transporte y Distribución',
  manufacturacolchonesysommiers:         'Manufactura · Colchones y Sommiers',
  modacalzado:                           'Moda · Calzado',
  modacalzadoyaccesorios:               'Moda · Calzado y Accesorios',
  modaropadeportiva:                     'Moda · Ropa Deportiva',
  modaropafemenina:                      'Moda · Ropa Femenina',
  modaropayaccesorios:                   'Moda · Ropa y Accesorios',
  ongdesarrolloeconomico:                'ONG · Desarrollo Económico',
  pinturasindustriaquimica:              'Pinturas · Industria Química',
  publicidadmarketing:                   'Publicidad y Marketing',
  publicidadproduccionymerchandising:    'Publicidad · Producción y Merchandising',
  religioninstitucionreligiosa:          'Religión · Institución Religiosa',
  retailautomotoresymotos:               'Retail · Automotores y Motos',
  retailcentrocomercial:                 'Retail · Centro Comercial',
  retailcombustibles:                    'Retail · Combustibles',
  retaildutyfree:                        'Retail · Duty Free',
  retailelectrodomesticos:               'Retail · Electrodomésticos',
  retailelectrodomesticosyhogar:         'Retail · Electrodomésticos y Hogar',
  retailelectronicaeimportacion:         'Retail · Electrónica e Importación',
  retailfarmacias:                       'Retail · Farmacias',
  retailferreteria:                      'Retail · Ferretería',
  retailferreteriayconstruccion:         'Retail · Ferretería y Construcción',
  retailhogaryconstruccion:              'Retail · Hogar y Construcción',
  retailmotosyelectrodomesticos:         'Retail · Motos y Electrodomésticos',
  retailmueblesydecoracion:              'Retail · Muebles y Decoración',
  retailmultitienda:                     'Retail · Multitienda',
  retailsupermercados:                   'Retail · Supermercados',
  saludcosmeticadermatologica:           'Salud · Cosmética Dermatológica',
  saluddistribuidorafarmaceutica:        'Salud · Distribuidora Farmacéutica',
  saludfarmaceutica:                     'Salud Farmacéutica',
  saludmedicina:                         'Salud · Medicina',
  saludmedicinalaboral:                  'Salud · Medicina Laboral',
  saludmedicinaprepaga:                  'Salud · Medicina Prepaga',
  saludodontologia:                      'Salud · Odontología',
  saludplanificacionfamiliar:            'Salud · Planificación Familiar',
  saludsanatorioprivado:                 'Salud · Sanatorio Privado',
  seguridadsistemasyelectronica:         'Seguridad · Sistemas y Electrónica',
  segurosaseguradora:                    'Seguros · Aseguradora',
  segurosjubilacionesypensiones:         'Seguros · Jubilaciones y Pensiones',
  servicioslogisticaexpress:             'Servicios · Logística Express',
  serviciostintoreria:                   'Servicios · Tintorería',
  tecnologiacamaraempresarial:           'Tecnología · Cámara Empresarial',
  tecnologiadelivery:                    'Tecnología · Delivery',
  tecnologiaelectronica:                 'Tecnología · Electrónica',
  tecnologiaelectronicayaccesorios:      'Tecnología · Electrónica y Accesorios',
  tecnologiaenergiayautomatizacion:      'Tecnología · Energía y Automatización',
  tecnologiainfraestructurait:           'Tecnología · Infraestructura IT',
  tecnologiamedios:                      'Tecnología · Medios',
  tecnologiaserviciosdigitales:          'Tecnología · Servicios Digitales',
  telecomunicaciones:                    'Telecomunicaciones',
};

const agencias = {
  ALEXPUBLICIDAD:          'Alex Publicidad',
  AUDIENCIA:               'Audiencia',
  BIEDERMANNPUBLICIDAD:    'Biedermann Publicidad',
  BMPUBLICIDAD:            'BM Publicidad',
  BMRM:                    'BMRM',
  BPUNTOCMARKETING:        'B Punto C Marketing',
  BRICK:                   'Brick',
  BSTRATEGICMEDIA:         'B Strategic Media',
  CAEIROCREA:              'Caeiro Crea',
  CMV:                     'CMV',
  COEFICIENTE:             'Coeficiente',
  CRITERIOPRODUCCIONES:    'Criterio Producciones',
  DATAGUAY:                'Dataguay',
  DDBNEEDHAM:              'DDB Needham',
  DEMARCA:                 'De Marca',
  DIRECTO:                 'Directo',
  ERNESTOGARCIA:           'Ernesto García',
  ESTRATEGA:               'Estratega',
  EURORSCG:                'Euro RSCG',
  FWDHAVASMEDIA:           'FWD Havas Media',
  GOIRIZIMAGENYCOMPANIA:   'Goiriz Imagen y Compañía',
  KNOUJAU:                 'Knoujau',
  LAMEDIA:                 'La Media',
  LINKEPUBLICIDAD:         'Linke Publicidad',
  LUCASICARDIPUBLICIDAD:   'Lucasi Cardi Publicidad',
  LUPE:                    'Lupe',
  MARKETANDSENSE:          'Market & Sense',
  MASSMEDIA:               'Mass Media',
  MASSPUBLICIDAD:          'Mass Publicidad',
  MEDIAADVANCEDPLANNING:   'Media Advanced Planning',
  MEDIABRAND:              'Media Brand',
  MRCOMUNICACIONES:        'MR Comunicaciones',
  MULTIMEDIACREATIVA:      'Multimedia Creativa',
  ONIRIA:                  'Oniria',
  PHD:                     'PHD',
  PRANA:                   'Prana',
  PUBLICITARIANASTA:       'Publicitaria Nasta',
  QUIROGAMEDIOS:           'Quiroga Medios',
  ROGER:                   'Roger',
  SENIOR:                  'Senior',
  SENIORPUBLICIDAD:        'Senior Publicidad',
  SERTRANSPUBLICIDAD:      'Sertrans Publicidad',
  SISTEMA7:                'Sistema 7',
  TABAREZ:                 'Tabarez',
  TEAMPUBLICIDAD:          'Team Publicidad',
  TURUPUBLICIDAD:          'Turu Publicidad',
};

const medios = {
  JORNAL:       'Jornal',
  RADIO:        'Radio',
  REVISTA:      'Revista',
  TVABERTA:     'TV Abierta',
  TVASSINATURA: 'TV Suscripción',
};

module.exports = { anunciantes, rubros, agencias, medios };
